{
    "openapi": "3.0.0",
    "info": {
        "title": "Project Fullstack",
        "description": "Documentation of project fullstack",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3000/"
        }
    ],
    "basePath": "/",
    "paths": {
        "/client": {
            "post": {
                "summary": "Add a new client",
                "tags": [
                    "Clients"
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "name": "Eva",
                                    "number": "35996874123",
                                    "email": "eva@gmail.com",
                                    "password": "123456789"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Returns the new Client",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "name": "Eva",
                                        "number": "35996874123",
                                        "email": "eva@gmail.com",
                                        "createdAt": "2023-05-29",
                                        "id": "1"
                                    }
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "E-mail already exists",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Email already exists"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "get": {
                "summary": "Get a list of clients",
                "tags": [
                    "Clients"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns all clients",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "examples": {
                                        "name": "Eva",
                                        "number": "35996874123",
                                        "email": "eva@gmail.com",
                                        "id": "1"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Missing bearer token",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Missing bearer token"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/client/{id}": {
            "patch": {
                "summary": "Updated a specific client",
                "tags": [
                    "Clients"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Client id",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "number": "21995567849"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Returns an updated client",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "name": "Eva",
                                        "number": "21995567849",
                                        "email": "eva@gmail.com",
                                        "id": "1"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Client not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Client not found"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Missing bearer token",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Missing bearer token"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete a client",
                "tags": [
                    "Clients"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Client id",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {}
                },
                "responses": {
                    "204": {
                        "description": "Confirms the client deletion"
                    },
                    "404": {
                        "description": "Client not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Client not found"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Missing bearer token",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Missing bearer token"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "summary": "Generate an access token",
                "tags": [
                    "Autentication"
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "email": "eva@gmail.com",
                                    "password": "123456789"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "JWT to handler user session",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjbGllbnRJZCI6NiwiaWF0IjoxNjg1NDcxNTIxLCJleHAiOjE2ODU1NTc5MjEsInN1YiI6IjYifQ.feCtg597EqnzYx2AnQQPeFcqIhCcIi0cCRgbRdZZ4A"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Wrong email or password",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Wrong email or password"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/client/{id}/contact": {
            "post": {
                "summary": "Add a new contact",
                "tags": [
                    "Contacts"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "name": "Alvaro",
                                    "number": "35996874123",
                                    "email": "alvaro@gmail.com",
                                    "password": "123456789"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Returns the new contact",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "name": "Alvaro",
                                        "number": "35996874123",
                                        "email": "alvaro@gmail.com",
                                        "createdAt": "2023-05-29",
                                        "id": "1"
                                    }
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "E-mail already exists",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Email already exists"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Missing bearer token",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Missing bearer token"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/client/contact": {
            "get": {
                "summary": "Get a list of contacts",
                "tags": [
                    "Contacts"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns all clients",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "examples": {
                                        "name": "Eva",
                                        "number": "35996874123",
                                        "email": "eva@gmail.com",
                                        "id": "1"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Missing bearer token",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Missing bearer token"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/client/contact/{id}": {
            "patch": {
                "summary": "Updated a specific contact",
                "tags": [
                    "Contacts"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Contact id",
                        "required": true
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "example": {
                                    "number": "12748965742"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Returns an updated contact",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "name": "Alvaro",
                                        "number": "12748965742",
                                        "email": "alvaro@gmail.com",
                                        "id": "1"
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Contact not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Contact not found"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Missing bearer token",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Missing bearer token"
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete a contact",
                "tags": [
                    "Contacts"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Contact id",
                        "required": true
                    }
                ],
                "requestBody": {},
                "responses": {
                    "204": {
                        "description": "Confirms the contact deletion"
                    },
                    "404": {
                        "description": "Contact not found",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Contact not found"
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Missing bearer token",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "example": {
                                        "message": "Missing bearer token"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}